CREATE TABLE PRICES (
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID   BIGINT         NOT NULL,
    START_DATE TIMESTAMP      NOT NULL,
    END_DATE   TIMESTAMP      NOT NULL,
    PRICE_LIST INTEGER        NOT NULL,
    PRODUCT_ID BIGINT         NOT NULL,
    PRIORITY   INTEGER        NOT NULL,
    PRICE      DECIMAL(20, 2) NOT NULL,
    CURR       VARCHAR(3)     NOT NULL
);

CREATE INDEX IDX_PRICES_LOOKUP ON PRICES (PRODUCT_ID, BRAND_ID, START_DATE, END_DATE);
